import './globals.css'
import Navbar from './navbar'
import Footer from './footer'

export const metadata = {
  title: 'Personal-Website',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1.0'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  )
}