import './globals.css'

export const metadata = {
  title: 'Personal-Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/school">School</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
